version: '2.2'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4'
    container_name: elasticsearch1
    environment:
      - cluster.name=atlantis-dl-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - 'esdata1:/usr/share/elasticsearch/data'
      - './elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
    ports:
      - '9200:9200'
    networks:
      - esnet
  elasticsearch2:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4'
    container_name: elasticsearch2
    environment:
      - cluster.name=atlantis-dl-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.ping.unicast.hosts=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - 'esdata2:/usr/share/elasticsearch/data'
      - './elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
    networks:
      - esnet
  elasticsearch3:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4'
    container_name: elasticsearch3
    environment:
      - cluster.name=atlantis-dl-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.ping.unicast.hosts=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - 'esdata3:/usr/share/elasticsearch/data'
      - './elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
    networks:
      - esnet
  kibana1:
    image: 'docker.elastic.co/kibana/kibana-oss:6.5.4'
    container_name: kibana
    links:
      - elasticsearch
    environment:
      - SERVER_NAME=monitorserver
      - SERVER_HOST=0.0.0.0
      - 'ELASTICSEARCH_URL=http://elasticsearch:9200'
    ports:
      - '5601:5601'
    volumes:
      - './kibana.yml:/usr/share/kibana/config/kibana.yml'
    networks:
      - esnet
    depends_on:
      - elasticsearch
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
networks:
  esnet: null
